# Define global parameters

# For main.py
WINDOW_WIDTH=2880
WINDOW_HEIGHT=1800
WIDTH_UNIT= round(WINDOW_WIDTH/100)
WINDOW_SIZE = WINDOW_WIDTH, WINDOW_HEIGHT
QUBIT_NUM=3
CIRCUIT_DEPTH=18


# For ball.py
LEFT = 0
RIGHT = 1

MEASURE_RIGHT = 1
MEASURE_LEFT = 2
NOTHING = 0

YES = 1
NO = 0

# For circuit_grid.py
GRID_WIDTH = WIDTH_UNIT * 4.96
GRID_HEIGHT = GRID_WIDTH

GATE_TILE_WIDTH = GRID_WIDTH * 0.76
GATE_TILE_HEIGHT = GATE_TILE_WIDTH

LINE_WIDTH = round(WIDTH_UNIT * 0.15)